version: '3.8'

services:
  # API FastAPI
  api:
    build: .
    container_name: books-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - ENVIRONMENT=development
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - books-network

  # Redis para cache (opcional)
  redis:
    image: redis:7-alpine
    container_name: books-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - books-network

volumes:
  redis-data:

networks:
  books-network:
    driver: bridge

